-- Stretch-goal schema changes for Biodiversity Hub.
-- Safe to run on a database that was already set up with the original setup.sql (every statement is idempotent).
-- Fresh databases get the same schema from setup.sql, so this file is only needed for existing projects.

-- Profiles carry email addresses, so only signed-in users may read them (the anon key alone cannot)
drop policy if exists "Public profiles are viewable by everyone." on profiles;
drop policy if exists "Profiles are viewable by signed-in users." on profiles;
create policy "Profiles are viewable by signed-in users." on profiles
  for select to authenticated using (true);

-- Stretch goal: endangered flag on species
alter table species add column if not exists endangered boolean not null default false;

-- Stretch goal: comments on species entries
create table if not exists comments (
  id bigint generated by default as identity primary key,
  species_id int not null references species on delete cascade,
  author uuid not null references profiles,
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists comments_species_id_created_at_idx on comments (species_id, created_at desc);

alter table comments enable row level security;

drop policy if exists "Comments are viewable by everyone." on comments;
create policy "Comments are viewable by everyone." on comments
  for select using (true);

drop policy if exists "Users can insert their own comments." on comments;
create policy "Users can insert their own comments." on comments
  for insert with check (auth.uid() = author);

drop policy if exists "Users can delete their own comments." on comments;
create policy "Users can delete their own comments." on comments
  for delete using (auth.uid() = author);
